from typing import TypedDict, Any, List, Dict, Tuple


class GraphState(TypedDict):
    """
    Central shared state for the LangGraph workflow.

    Every node/agent in the graph:
    - reads values from this state
    - updates only the fields it is responsible for

    This acts as the single source of truth across the
    entire AI data analysis pipeline.
    """

    # ============================================================
    # INPUT / INGESTION
    # ============================================================

    # Absolute or relative path of the uploaded dataset.
    # Example:
    # "data/sales.csv"
    file_path: str

    # Detected dataset format.
    # Set by the Ingestion Node.
    #
    # Possible values:
    # - "csv"
    # - "excel"
    # - "json"   
    file_type: str

    # ============================================================
    # DATA STORAGE
    # ============================================================

    # Original raw dataframe directly loaded from source.
    # NEVER modify this dataframe.
    #
    # Purpose:
    # - debugging
    # - rollback
    # - audit trail
    # - comparison against cleaned data
    raw_df: Any

    # Cleaned and processed dataframe after:
    # - missing value handling
    # - duplicate removal
    # - datatype fixing
    # - normalization
    #
    # All downstream analytics should use this dataframe.
    clean_df: Any

    # ============================================================
    # SCHEMA / STRUCTURE INFORMATION
    # ============================================================

    # List of dataset column names.
    #
    # Example:
    # ["customer_id", "sales", "date"]
    columns: List[str]

    # Dictionary mapping column names to datatype strings.
    #
    # Example:
    # {
    #     "sales": "float64",
    #     "date": "datetime64[ns]"
    # }
    #
    # Used by:
    # - Dataset Understanding Agent
    # - Analytics Agent
    # - Cleaning Node
    dtypes: Dict[Any, Any]

    # Shape of dataframe.
    #
    # Format:
    # (rows, columns)
    #
    # Example:
    # (10000, 15)
    shape: Tuple[int, int]

    # ============================================================
    # DATA SAMPLING
    # ============================================================

    # First N rows of dataset converted to dictionaries.
    #
    # Used for:
    # - dataset understanding
    # - debugging
    # - LLM context
    #
    # Example:
    # [
    #     {"sales": 100, "region": "US"},
    #     {"sales": 200, "region": "EU"}
    # ]
    top_rows: List[Dict[str, Any]]

    # Last N rows of dataset converted to dictionaries.
    #
    # Helps detect:
    # - formatting inconsistencies
    # - footer corruption
    # - trailing anomalies
    bottom_rows: List[Dict[str, Any]]

    # ============================================================
    # DATA PROFILING / STATISTICS
    # ============================================================

    # Missing/null value summary for each column brfore cleaning.
    #
    # Example:
    # {
    #     "sales": 0,
    #     "customer_id": 12
    # }
    #
    # Used heavily by Cleaning Node.
    raw_missing_summary: Dict[Any, Any]
    
    # ============================================================
    
    # Missing/null value summary for each column after cleaning.
    #
    # Example:
    # {
    #     "sales": 0,
    #     "customer_id": 12
    # }
    #
    # Used heavily by Cleaning Node.
    clean_missing_summary: Dict[Any, Any]

    # Statistical summary of dataset.
    #
    # Generated using:
    # df.describe(include="all")
    #
    # Can include:
    # - mean
    # - std
    # - min/max
    # - unique counts
    # - frequencies
    statistical_summary: Dict[str, Any]

    # ============================================================
    # AI DATASET UNDERSTANDING
    # ============================================================

    # High-level natural language summary of the dataset.
    #
    # Generated by Dataset Understanding Agent.
    #
    # Example:
    # "This appears to be retail sales data containing
    # customer purchases across multiple regions."
    dataset_summary: str

    # Predicted business domain/category of dataset.
    #
    # Example:
    # - "finance"
    # - "healthcare"
    # - "retail"
    # - "marketing"
    business_domain: str

    # Recommended analytics or ML tasks inferred by AI.
    #
    # Example:
    # [
    #     "sales forecasting",
    #     "customer segmentation",
    #     "churn prediction"
    # ]
    recommended_tasks: List[str]

    # ============================================================
    # ANALYTICS / MACHINE LEARNING
    # ============================================================

    # Statistical and analytical outputs generated by
    # Analytics Agent.
    #
    # Example:
    # {
    #     "correlations": {...},
    #     "kpis": {...},
    #     "trends": {...}
    # }
    analytics_results: Dict[str, Any]

    # Outputs generated from ML models.
    #
    # Example:
    # {
    #     "forecast": [...],
    #     "accuracy": 0.91,
    #     "feature_importance": {...}
    # }
    ml_results: Dict[str, Any]

    # ============================================================
    # VISUALIZATION OUTPUTS
    # ============================================================

    # List of generated chart file paths.
    #
    # Example:
    # [
    #     "charts/revenue_trend.html",
    #     "charts/churn_heatmap.png"
    # ]
    #
    # Generated by Visualization Node.
    charts: List[str]

    # ============================================================
    # BUSINESS INSIGHTS
    # ============================================================

    # AI-generated business insights derived from:
    # - analytics
    # - ML outputs
    # - trends
    # - correlations
    #
    # Example:
    # [
    #   "Revenue declined mainly in Region A.",
    #   "Customer retention strongly impacts sales."
    # ]
    insights: List[str]

    # AI-generated business/action recommendations.
    #
    # Example:
    # [
    #   "Increase retention campaigns in Region A.",
    #   "Reduce inventory for low-demand products."
    # ]
    recommendations: List[str]

    # ============================================================
    # VALIDATION / QUALITY ASSURANCE
    # ============================================================

    # Stores validation and quality checks across pipeline.
    #
    # Example:
    # {
    #     "missing_charts": False,
    #     "ml_training_success": True,
    #     "report_complete": True
    # }
    #
    # Generated by Validation Node.
    validation_results: Dict[str, Any]

    # ============================================================
    # FINAL OUTPUT
    # ============================================================

    # Path to generated final report.
    #
    # Example:
    # "reports/final_report.html"
    #
    # Can point to:
    # - HTML report
    # - PDF report
    # - notebook
    report_path: str